import {
  analyzeOrgAccessReview,
  highestSeverity,
  type Finding,
} from "@/lib/access-analysis";
import { CONTROL_CATALOG } from "@/lib/controls";
import { toCsv } from "@/lib/csv";

type SnapshotInput = {
  collectedAt: Date;
  data: Record<string, unknown>;
};

type OrgEntry = Record<string, unknown>;
type Member = Record<string, unknown>;

function s(v: unknown): string {
  return v != null ? String(v) : "";
}

function getOrgs(data: Record<string, unknown>): OrgEntry[] {
  return Array.isArray(data.orgs)
    ? (data.orgs as OrgEntry[])
    : [];
}

function getMembers(entry: OrgEntry): Member[] {
  return Array.isArray(entry.members)
    ? (entry.members as Member[])
    : [];
}

// ---------------------------------------------------------------------------
// Metrics
// ---------------------------------------------------------------------------

export type PackMetrics = {
  collectedAt: string;
  orgCount: number;
  memberCount: number;
  adminCount: number;
  repoCount: number;
  prCount: number;
  warningCount: number;
  highestSeverity: string | null;
  findingsBySeverity: Record<string, number>;
};

function getRepos(entry: OrgEntry): Record<string, unknown>[] {
  return Array.isArray(entry.repos) ? (entry.repos as Record<string, unknown>[]) : [];
}

function getPRs(entry: OrgEntry): Record<string, unknown>[] {
  return Array.isArray(entry.pullRequests) ? (entry.pullRequests as Record<string, unknown>[]) : [];
}

function computeMetrics(
  snapshot: SnapshotInput,
  findings: Finding[],
): PackMetrics {
  const orgs = getOrgs(snapshot.data);
  let memberCount = 0;
  let adminCount = 0;
  let repoCount = 0;
  let prCount = 0;

  for (const entry of orgs) {
    const members = getMembers(entry);
    memberCount += members.length;
    adminCount += members.filter((m) => String(m.role) === "admin").length;
    repoCount += getRepos(entry).length;
    prCount += getPRs(entry).length;
  }

  const bySeverity: Record<string, number> = {};
  for (const f of findings) {
    bySeverity[f.severity] = (bySeverity[f.severity] ?? 0) + 1;
  }

  return {
    collectedAt: snapshot.collectedAt.toISOString(),
    orgCount: orgs.length,
    memberCount,
    adminCount,
    repoCount,
    prCount,
    warningCount: findings.length,
    highestSeverity: highestSeverity(findings),
    findingsBySeverity: bySeverity,
  };
}

// ---------------------------------------------------------------------------
// README
// ---------------------------------------------------------------------------

function buildReadme(metrics: PackMetrics): string {
  const lines = [
    "# ProofFlow Evidence Pack",
    "",
    "## GitHub Organization Access Review",
    "",
    `**Collected at:** ${metrics.collectedAt}`,
    "",
    "### Summary",
    "",
    `| Metric | Value |`,
    `| --- | --- |`,
    `| Organizations analyzed | ${metrics.orgCount} |`,
    `| Total members | ${metrics.memberCount} |`,
    `| Total admins | ${metrics.adminCount} |`,
    `| Repositories | ${metrics.repoCount} |`,
    `| Recent pull requests | ${metrics.prCount} |`,
    `| Risk warnings | ${metrics.warningCount} |`,
    `| Highest severity | ${metrics.highestSeverity ?? "none"} |`,
    "",
    "### Contents",
    "",
    "- `README.md` — this file",
    "- `org-access-review.csv` — member list with roles, one row per user",
    "- `repo-access.csv` — repository list with visibility and permissions",
    "- `pull-requests.csv` — recent pull requests with authors and review status",
    "- `risk-summary.json` — structured risk analysis findings",
    "- `raw-snapshot.json` — full collected snapshot data",
    "",
    "### Compliance Mapping",
    "",
    "This evidence supports the following controls:",
    "",
    ...CONTROL_CATALOG.map(
      (c) => `- **${c.framework} ${c.code}** \u2014 ${c.name}`,
    ),
    "",
    "### How to use",
    "",
    "This evidence pack captures the GitHub organization membership, repository",
    "access, and change management state at the time of collection.",
    "",
    "The risk summary highlights potential access issues such as excessive admin",
    "accounts, bot accounts with admin privileges, or single points of failure.",
    "",
    "The pull request data demonstrates that changes go through a review process,",
    "supporting change management controls (CC8.1).",
    "",
    "Manual evidence uploads (if any) provide additional coverage for controls",
    "that lack automated collection, such as monitoring or change management.",
    "",
    "---",
    "*Generated by ProofFlow*",
    "",
  ];
  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// CSV (reuses the same format as the export route)
// ---------------------------------------------------------------------------

function buildCsv(snapshot: SnapshotInput): string {
  const headers = [
    "collected_at",
    "org_login",
    "org_id",
    "user_login",
    "user_id",
    "user_type",
    "role",
  ];

  const collectedAt = snapshot.collectedAt.toISOString();
  const orgs = getOrgs(snapshot.data);
  const rows: string[][] = [];

  for (const entry of orgs) {
    const org = (entry.org ?? {}) as Record<string, unknown>;
    const members = getMembers(entry);

    if (members.length === 0) {
      rows.push([collectedAt, s(org.login), s(org.id), "", "", "", ""]);
    } else {
      for (const m of members) {
        rows.push([
          collectedAt,
          s(org.login),
          s(org.id),
          s(m.login),
          s(m.id),
          s(m.type),
          s(m.role),
        ]);
      }
    }
  }

  if (rows.length === 0) {
    rows.push([collectedAt, "", "", "", "", "", ""]);
  }

  return toCsv(headers, rows);
}

// ---------------------------------------------------------------------------
// Repo access CSV
// ---------------------------------------------------------------------------

function buildRepoCsv(snapshot: SnapshotInput): string {
  const headers = [
    "collected_at",
    "org_login",
    "repo_name",
    "repo_id",
    "private",
    "archived",
    "default_branch",
    "pushed_at",
  ];

  const collectedAt = snapshot.collectedAt.toISOString();
  const orgs = getOrgs(snapshot.data);
  const rows: string[][] = [];

  for (const entry of orgs) {
    const org = (entry.org ?? {}) as Record<string, unknown>;
    const repos = getRepos(entry);
    for (const r of repos) {
      rows.push([
        collectedAt,
        s(org.login),
        s(r.name),
        s(r.id),
        String(Boolean(r.private)),
        String(Boolean(r.archived)),
        s(r.default_branch),
        s(r.pushed_at),
      ]);
    }
  }

  return toCsv(headers, rows);
}

// ---------------------------------------------------------------------------
// Pull requests CSV
// ---------------------------------------------------------------------------

function buildPrCsv(snapshot: SnapshotInput): string {
  const headers = [
    "collected_at",
    "org_login",
    "repo",
    "pr_number",
    "title",
    "state",
    "author",
    "created_at",
    "merged_at",
    "reviewers",
  ];

  const collectedAt = snapshot.collectedAt.toISOString();
  const orgs = getOrgs(snapshot.data);
  const rows: string[][] = [];

  for (const entry of orgs) {
    const org = (entry.org ?? {}) as Record<string, unknown>;
    const prs = getPRs(entry);
    for (const pr of prs) {
      const reviewers = Array.isArray(pr.reviewers)
        ? (pr.reviewers as string[]).join("; ")
        : "";
      rows.push([
        collectedAt,
        s(org.login),
        s(pr.repo),
        s(pr.number),
        s(pr.title),
        s(pr.state),
        s(pr.author),
        s(pr.created_at),
        s(pr.merged_at),
        reviewers,
      ]);
    }
  }

  return toCsv(headers, rows);
}

// ---------------------------------------------------------------------------
// Risk summary JSON
// ---------------------------------------------------------------------------

function buildRiskSummary(
  metrics: PackMetrics,
  findings: Finding[],
): string {
  return JSON.stringify(
    {
      evidenceType: "github_org_access_review",
      collectedAt: metrics.collectedAt,
      summary: {
        orgCount: metrics.orgCount,
        memberCount: metrics.memberCount,
        adminCount: metrics.adminCount,
        warningCount: metrics.warningCount,
        highestSeverity: metrics.highestSeverity,
        findingsBySeverity: metrics.findingsBySeverity,
      },
      findings,
    },
    null,
    2,
  );
}

// ---------------------------------------------------------------------------
// Public API: build all pack files
// ---------------------------------------------------------------------------

export type PackFile = {
  name: string;
  content: string;
};

export function buildEvidencePackFiles(snapshot: SnapshotInput): PackFile[] {
  const findings = analyzeOrgAccessReview(snapshot.data);
  const metrics = computeMetrics(snapshot, findings);

  return [
    { name: "README.md", content: buildReadme(metrics) },
    { name: "org-access-review.csv", content: buildCsv(snapshot) },
    { name: "repo-access.csv", content: buildRepoCsv(snapshot) },
    { name: "pull-requests.csv", content: buildPrCsv(snapshot) },
    { name: "risk-summary.json", content: buildRiskSummary(metrics, findings) },
    {
      name: "raw-snapshot.json",
      content: JSON.stringify(snapshot.data, null, 2),
    },
  ];
}
