import {
  analyzeOrgAccessReview,
  highestSeverity,
  type Finding,
} from "@/lib/access-analysis";
import { toCsv } from "@/lib/csv";

type SnapshotInput = {
  collectedAt: Date;
  data: Record<string, unknown>;
};

type OrgEntry = Record<string, unknown>;
type Member = Record<string, unknown>;

function s(v: unknown): string {
  return v != null ? String(v) : "";
}

function getOrgs(data: Record<string, unknown>): OrgEntry[] {
  return Array.isArray(data.orgs)
    ? (data.orgs as OrgEntry[])
    : [];
}

function getMembers(entry: OrgEntry): Member[] {
  return Array.isArray(entry.members)
    ? (entry.members as Member[])
    : [];
}

// ---------------------------------------------------------------------------
// Metrics
// ---------------------------------------------------------------------------

export type PackMetrics = {
  collectedAt: string;
  orgCount: number;
  memberCount: number;
  adminCount: number;
  warningCount: number;
  highestSeverity: string | null;
  findingsBySeverity: Record<string, number>;
};

function computeMetrics(
  snapshot: SnapshotInput,
  findings: Finding[],
): PackMetrics {
  const orgs = getOrgs(snapshot.data);
  let memberCount = 0;
  let adminCount = 0;

  for (const entry of orgs) {
    const members = getMembers(entry);
    memberCount += members.length;
    adminCount += members.filter((m) => String(m.role) === "admin").length;
  }

  const bySeverity: Record<string, number> = {};
  for (const f of findings) {
    bySeverity[f.severity] = (bySeverity[f.severity] ?? 0) + 1;
  }

  return {
    collectedAt: snapshot.collectedAt.toISOString(),
    orgCount: orgs.length,
    memberCount,
    adminCount,
    warningCount: findings.length,
    highestSeverity: highestSeverity(findings),
    findingsBySeverity: bySeverity,
  };
}

// ---------------------------------------------------------------------------
// README
// ---------------------------------------------------------------------------

function buildReadme(metrics: PackMetrics): string {
  const lines = [
    "# ProofFlow Evidence Pack",
    "",
    "## GitHub Organization Access Review",
    "",
    `**Collected at:** ${metrics.collectedAt}`,
    "",
    "### Summary",
    "",
    `| Metric | Value |`,
    `| --- | --- |`,
    `| Organizations analyzed | ${metrics.orgCount} |`,
    `| Total members | ${metrics.memberCount} |`,
    `| Total admins | ${metrics.adminCount} |`,
    `| Risk warnings | ${metrics.warningCount} |`,
    `| Highest severity | ${metrics.highestSeverity ?? "none"} |`,
    "",
    "### Contents",
    "",
    "- `README.md` — this file",
    "- `org-access-review.csv` — member list with roles, one row per user",
    "- `risk-summary.json` — structured risk analysis findings",
    "- `raw-snapshot.json` — full collected snapshot data",
    "",
    "### How to use",
    "",
    "This evidence pack captures the GitHub organization membership state at the",
    "time of collection. It can be provided to auditors as proof of access review.",
    "",
    "The risk summary highlights potential access issues such as excessive admin",
    "accounts, bot accounts with admin privileges, or single points of failure.",
    "",
    "---",
    "*Generated by ProofFlow*",
    "",
  ];
  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// CSV (reuses the same format as the export route)
// ---------------------------------------------------------------------------

function buildCsv(snapshot: SnapshotInput): string {
  const headers = [
    "collected_at",
    "org_login",
    "org_id",
    "user_login",
    "user_id",
    "user_type",
    "role",
  ];

  const collectedAt = snapshot.collectedAt.toISOString();
  const orgs = getOrgs(snapshot.data);
  const rows: string[][] = [];

  for (const entry of orgs) {
    const org = (entry.org ?? {}) as Record<string, unknown>;
    const members = getMembers(entry);

    if (members.length === 0) {
      rows.push([collectedAt, s(org.login), s(org.id), "", "", "", ""]);
    } else {
      for (const m of members) {
        rows.push([
          collectedAt,
          s(org.login),
          s(org.id),
          s(m.login),
          s(m.id),
          s(m.type),
          s(m.role),
        ]);
      }
    }
  }

  if (rows.length === 0) {
    rows.push([collectedAt, "", "", "", "", "", ""]);
  }

  return toCsv(headers, rows);
}

// ---------------------------------------------------------------------------
// Risk summary JSON
// ---------------------------------------------------------------------------

function buildRiskSummary(
  metrics: PackMetrics,
  findings: Finding[],
): string {
  return JSON.stringify(
    {
      evidenceType: "github_org_access_review",
      collectedAt: metrics.collectedAt,
      summary: {
        orgCount: metrics.orgCount,
        memberCount: metrics.memberCount,
        adminCount: metrics.adminCount,
        warningCount: metrics.warningCount,
        highestSeverity: metrics.highestSeverity,
        findingsBySeverity: metrics.findingsBySeverity,
      },
      findings,
    },
    null,
    2,
  );
}

// ---------------------------------------------------------------------------
// Public API: build all pack files
// ---------------------------------------------------------------------------

export type PackFile = {
  name: string;
  content: string;
};

export function buildEvidencePackFiles(snapshot: SnapshotInput): PackFile[] {
  const findings = analyzeOrgAccessReview(snapshot.data);
  const metrics = computeMetrics(snapshot, findings);

  return [
    { name: "README.md", content: buildReadme(metrics) },
    { name: "org-access-review.csv", content: buildCsv(snapshot) },
    { name: "risk-summary.json", content: buildRiskSummary(metrics, findings) },
    {
      name: "raw-snapshot.json",
      content: JSON.stringify(snapshot.data, null, 2),
    },
  ];
}
